[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
Gabs = "0eb812ee-a11f-4f5e-b8d4-bb8a44f06f50"
QuantumInterface = "5717a53b-5d69-4fa3-b976-0bf2f97ca1e5"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
